### ISSUE TITLE
Add --config in order to allow usage of another configuration file

### ISSUE THREAD

**Issue by SR-G** [SR-G/sleep-on-lan#10]
Add a --config parameter.
See if it is worth switching to the regular spf13/cobra framework.

**Comment by lkd70** [comment]
At the moment I just do:
`./sol configfilename.json`
It's not ideal, but was easier to implement than relying on another package to handle command line argument parsing.

**Comment by SR-G** [comment]
Implemented in 1.0.6-SNAPSHOT
