### ISSUE TITLE
@reb

### ISSUE THREAD

**Issue by supereggbert** [SR-G/sleep-on-lan#14]
Works well when run at command line but when trying to use supervisor the server clearly starts as I'm getting a response:
`<result>
<application>sleep-on-lan</application>
<hosts>
<host ip="fe80::c23f:d5ff:fea0:94f0/64" mac="c0:3f:d5:a0:94:f0"/>
<host ip="10.71.10.6/32" mac=""/>
<host ip="127.0.0.1/8" mac=""/>
<host ip="::1/128" mac=""/>
<host ip="192.168.0.128/24" mac="c0:3f:d5:a0:94:f0"/>
<host ip="192.168.11.5/24" mac="c0:3f:d5:a0:94:f0"/>
</hosts>
<listeners>
<listener type="UDP" port="9" active="true"/>
<listener type="UDP" port="7" active="true"/>
<listener type="HTTP" port="8009" active="true"/>
</listeners>
</result>`

But when calling /sleep/ nothing happens, I just get the same response above. Unlike when I start from the command line, so I'm quite confused. Supervisor conf is as simple as they come:
`[program:cat]
command=/home/main/SleepOnLAN-1.0.0-SNAPSHOT/linux/sol`

PS I'm running debian.

Any Ideas?

**Comment by SR-G** [comment]
I really don't know.

I just made a try on my side (alpine docker container 3.7 + supervisord) with this configuration and everything seems to be working fine.

Configuration in `/etc/supervisor.d/sleep-on-lan.ini` : 
```
[program:sleep-on-lan] 
command=/go/bin/sol 
stdout_logfile =/var/log/supervisord_sleep-on-lan.log
redirect_stderr=true
```

Test done through : 
```
curl localhost:8009/sleep
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <operation>sleep</operation>
  <successful>true</successful>
</result>
```

Result in `/var/log/supervisord_sleep-on-lan.log` is : 
```
INFO: 2017/11/26 12:24:23 listener_udp.go:12: Now listening UDP packets on port [9]
INFO: 2017/11/26 12:24:47 listener_http.go:138: Executing [sleep]
INFO: 2017/11/26 12:24:47 sleeper_linux.go:10: Executing operation [sleep], type [pm-suspend], command [pm-suspend]
INFO: 2017/11/26 12:24:47 sleeper_linux.go:21: Sleep implementation [linux], sleep command is [pm-suspend]
ERROR: 2017/11/26 12:24:47 sleeper_linux.go:24: Can't execute command [pm-suspend] : exec: "pm-suspend": executable file not found in $PATH
```

(expected error as i don't have the pm-suspend command installed in this test container)

you should test again with supervisord logs configured to see what's going on. Either the command is not correctly executed (path error, and so on), either the `pm-suspend` is not working as expected when executed through a supervisor sub-process (but i don't see any reason for this not to be working).

**Comment by supereggbert** [comment]
Thanks, just done some more digging and I think I found the issue, in case anyone else has problem; it seems to be working but takes a couple of additional minutes after SOL has launched. Just a guess but supervisor may be starting the server before acpid is up and running.
