### ISSUE TITLE
4 command executions for 1 sent UDP packet ?

### ISSUE THREAD

**Issue by girque** [SR-G/sleep-on-lan#16]
Hi, 
First of all thank you for this projet, it's very useful.

When I send 1 "UDP SoL packet" (with Mocha VNC Lite on iPhone), it results (after the log info) with 4 executions of the shutdown command in my case. The server shutdowns correctly but there is a quite annoying issue. If I try to restart the computer immediately (WoL packet), it's shut down again after several seconds.
My guess is the others UDP SoL packets were stuck in some buffer and once the network card is up it is turned off again. Is that possible? 
Could it be that I ran the service 4 times and badly killed it? (even after rebooting.. I don't think so)

Log errors are just a user permission issue. This log is the result of 1 UDP SoL packet, is it normal it executes 4 times ?

<img width="349" alt="capture d ecran 2017-12-20 a 11 27 40" src="https://user-images.githubusercontent.com/6932264/34202941-9fc490c2-e579-11e7-9fcd-aab57a8be638.png">

Some features you could add:
-A REST "login page" to secure the Sleep on Wan
-A REST page to know the machine state (on/off)

**Comment by girque** [comment]
Maybe the user permission issue was the source of the problem after all:

* I followed [this tutorial](http://how-to.wikia.com/wiki/How_to_allow_non-super_users_to_shutdown_computer_in_Linux) to allow non-root user to be able to execute the command `sudo shutdown -h now`
* I also changed the ownership of the /var/log/sleep-on-lan.log to be able  to launch the `nohup /path/to/sol_binary > /var/log/sleep-on-lan.log 2>&1 &` as non-root
* The SoL followed by immediate WoL worked well (in my case SoW and WoW)
* The log file now only shows 1 command execution for 1 UDP SoL packet sent

**Comment by SR-G** [comment]
Ok hadn't time to investigate your main issue (which i've never encountered on my side), glad you solved it by yourself.

For non-root execution, i was suggesting the `setcap` method in the global README.md (https://github.com/SR-G/sleep-on-lan), but other methods may of course work.

For your additional comments : 

- A Basic Auth has just been added (see #17), but new SNAPSHOT not uploaded yet
- For a "REST state", could be nice but i don't see how to do that : i can easily add a "/isUpAndRunning/" HTTP method, but the "/isAsleep" will never work as soon as the server you're trying to reach is offline ... or were you speaking about a "/state/<MAC_ADDRESS>/" command that would remotely tells the state of another remote server (would then probably just be a wrapper around some kind of ping commands) ?

**Comment by girque** [comment]
Yes I followed the `setcap` technique to listen on port 9. But still permissions to write in /var/log/sleep-on-lan.log and also use `shutdown` command are needed. As you said there are many methods..

* Thank you for the Basic Auth, it will allow to use HTTP for SoW. It's more reliable than UDP packets.
* Yes exactly I was talking about a kind of "ping wrapper" called by a "/isUpAndRunning/" HTTP method. Then a simple browser is enough to get this boolean value (no console needed). For example in case someone else is using the computer maybe it is better to do not shut it down.

**Comment by SR-G** [comment]
Ok, would #18 do the trick, could you review it ? (already coded, awaiting to see if it would meet your needs)

Would allow : 
- to see if the server where sol is running is online or offline (immediate result)
- to see if another server is online or offline (will execute a IMCP request to the remote IP)

Questionning another server through MAC addresses rather than IP would be possible but a little bit more complicated (would need to know which network interface to use in order to make the ARP query on).

**Comment by girque** [comment]
Yes it is perfect like this. We can get the status of other computers in the local network. No need to NAT/PAT them all to ping them, quite useful and simple.
I suggest you update the doc accordingly when released ;) 
Cheers !
