### ISSUE TITLE
Fedora 30 not receiving magic packets on UDP

### ISSUE THREAD

**Issue by evertonstz** [SR-G/sleep-on-lan#23]
The binary runs fine and it's being run with sudo, I get no errors but doesn't seems to be seeing the mp I'm sending it from my linux laptop. I double checked to see if it wasn't a typo in the reversed mac, but no. Here's the output:

https://pastebin.com/CjCPLa6B

Could it be firewalld blocking the script? I have no knowledge on  how to whitelist a binary in it tho. WOL works fine btw.

**Comment by SR-G** [comment]
(necro-resurrecting issue to close it) I have no idea ...

A few hints : 
- it could be your wake-on-lan tooling/script not forwarding to .255.255
- it could be some firewall issues (i've never encountered some)
- reversed mac address are now displayed (in start logs + in HTTP "/" endpoint) for convenience

The question is really : is there anything displayed by the sleep-on-lan binary when magic packets are sent ? (or nothing in the logs)

Additionnaly : 
- you would use wireshark to see which packets are sent
- at the very worst, you could use the HTTP endpoint as a workaround (http://<ip>:<port>/sleep)
