### ISSUE TITLE
No response for HTTP sleep

### ISSUE THREAD

**Issue by mastermarkhun** [SR-G/sleep-on-lan#47]
Hey,

When I call the sleep URL with curl, the curl don't get any response and just hanging. The computer immediately goes into sleep however.

This is causing HomeBridge thinks the command failed.

Could this URL give back a 200 OK blank page or something? This should solve this.

Thanks,
Mark

**Comment by SR-G** [comment]
Yes, ok, please check 1.1.1-RELEASE, per #48

**Comment by mastermarkhun** [comment]
Works like a charm. :)
Thank you very much.
