### ISSUE TITLE
Wake on LAN works strange when service work

### ISSUE THREAD

**Issue by strangesound** [SR-G/sleep-on-lan#50]
I opened sol.exe, put to sleep works OK. But wake up works strangely. Computer starts and sleep after couple seconds. Why?

**Comment by SR-G** [comment]
Per previous informations from other people using it : 
- it seems your client is sending several times the packets (first one trapped immediately, other ones trapped at resume)
- check if you have activated (as written on first page / documentation) for a workaround "AvoidDualUDPSending")
Closing for now.
