### ISSUE TITLE
VirusTotal scan results

### ISSUE THREAD

**Issue by kingp0dd** [SR-G/sleep-on-lan#53]
https://www.virustotal.com/gui/file/3c4884349b679ffa9b15652f1a42044919932d901ae40ee730877958958eb340

Any idea why it's getting a hit?

**Comment by SR-G** [comment]
I have 0 ideas / never got any report myself about this (and i'm using this WINDOWS binary on WIN10 / WIN11 with up-to-date microsoft defender virus definitions) (+ on linux of course).

Indeed if i take from GITHUB releases the very latest 1.1.1 RELEASE distribution, then upload the sol.exe (for which the hash is `cksum sol.exe` > `1318573868 8514048 sol.exe`), i have the same report than you through that platform.
![image](https://github.com/SR-G/sleep-on-lan/assets/194141/2d8c3fa0-829c-4552-b639-9eef21cb89fa)

However Virusscan is not finding anything with the same binary : 
![image](https://github.com/SR-G/sleep-on-lan/assets/194141/84db59fe-210b-49c2-8eae-d5273306fdaa)

So i would say this is definitely a wrong detection - it seems "virustotal" is considering the code allowing the launch of external command (which is one the core feature of the binary, allowing to configure any command through configuration and that is then executed (forked) when the WAN MAC address is received, or when the corresponding HTTP REST call is triggered) as a potential security risk : 

![image](https://github.com/SR-G/sleep-on-lan/assets/194141/49be7ae3-8302-42c3-977e-6e5cdc267f34)

And of course, you can compile the code by yourself (after reviewing the code) if you are not trusting the release.
