### ISSUE TITLE
Build binaries for x86 architecture

### ISSUE THREAD

**Issue by pierdom** [SR-G/sleep-on-lan#55]
Thank your for this great project. I have it running on an x86_64 machine, but I would also like to use it on an older Synology NAS with Intel x86 CPU.

I noticed the snapshots do not include linux x86 and I don't have an x86 machine to compile it on (besides the NAS itself, but getting golang to work there would be close to impossible).

In short: could you please add support for linux x86?
Thank you again.

**Comment by SR-G** [comment]
Hello.
You should now see it in this pre-release : https://github.com/SR-G/sleep-on-lan/releases
I have no LINUX/i386 box anymore so can't test, but it should work.

By the way and just FYI, you could have cross-compiled on your side just with (this is exactly what i'm doing anyway : generating all the binaries for all operating systems from one same linux platform, per the golang cross-compilation capacities) : 

``` 
GOARCH=386 GOOS=linux go install -a -tags netgo -installsuffix netgo sleep-on-lan
```
