### ISSUE TITLE
Confirmation Dialog

### ISSUE THREAD

**Issue by MarvinT** [SR-G/sleep-on-lan#6]
Awesome program.  A really useful feature would be to display a confirmation dialog on the computer that was being put to sleep so that a user wouldn't be unexpectedly get locked out. I could imagine opening a dialog window on computer that timed out after 30 seconds allowing the user to cancel the sleep request. Thanks!

**Comment by SR-G** [comment]
Seems out of scope / i don't see any easy way to do that.
